name: Verify Secrets

on: 
    push:        # Trigger on push
    workflow_dispatch:   # Manual trigger

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Test secrets
        env:
            TEST: ${{ secrets.TEST }}
        run: echo "TEST=${{ secrets.TEST }}"


      - name: Verify Secrets
        env:
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          echo "DASHBOARD_URL is set"
          echo "EMAIL_RECIPIENT is set"
          echo "JIRA_API_TOKEN is set"
          echo "JIRA_BASE_URL is set"
          echo "JIRA_EMAIL is set"
          echo "PROJECT_KEY is set"
          echo "SMTP_EMAIL is set"
          echo "SMTP_PASSWORD is set"
